application:
  version: @appVersion@

server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s

  datasource:
    driverClassName: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  web:
    logging:
      level: DEBUG
      enable: true

management:
  server:
    port: 8081
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always

  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  health:
    db:
      enabled: false
    diskspace:
      enabled: false
    ping:
      enabled: false
  info:
    git:
      enabled: true
      mode: simple
